---
# vars file for sssd

sss_packages:
  - authconfig
  - sssd

sss_allowed_groups:
  - admins

sss_ldap_hosts:
  - 'controller.cluster'

sss_filter_enabled: true

ca_certificate_path: /etc/openldap/certs/
ldap_conf: /etc/openldap/ldap.conf

sssd_config_location: /etc/sssd

sss_use_ds389: false
