---
ldap_auth: false

enable_ssl: false
grafana_port: 3000

# Theme is light or dark
grafana_theme: 'light'
grafana_org_name: TrinityX
grafana_login_hint: 'TrinityX username'
grafana_admin: 'admin'
# Make all dashboards available (view only)
anonymous_access: true
ssl_certificate: /etc/pki/tls/certs/localhost.crt
ssl_certificate_key: /etc/pki/tls/private/localhost.key

grafana_dashboard_dir: /var/lib/grafana/dashboards
grafana_dashboards:
  - trinityx-home.json
  - trinityx-sysinfo-detail.json
  - trinityx-workloadmanagement.json
