---

- name: Ensure pip and setuptools are installed
  package:
    name: "{{ crypt_req }}"
    state: present

- name: Install passlib with bcrypt support
  pip:
    name: "{{ crypt_packages }}"
    state: present
    executable: pip3

