---
# vars file for luna2

luna2_packages:
  - luna2-python
  - luna2-grub2-autofind
#  - luna2-daemon
#  - luna2-cli

required_packages:
  - dhcp-server
  - xinetd
  - sqlite
  - dos2unix
  - tftp-server
  - net-snmp-utils

enable_services:
  - xinetd
  - dhcpd
  - nginx

start_services:
  - xinetd
  - dhcpd
  - nginx

luna2_use_kea: false

# commenting out both next values will use index/repo defaults, i.e. latest, greatest
luna2_daemon_pip: luna2_daemon-2.1-py3-none-any.whl
luna2_cli_pip: luna2_cli-2.1-py3-none-any.whl
luna2_utils_pip: luna2_utils-2.1-py3-none-any.whl

luna2_utils:
  - lchroot
  - lcluster
  - lpower
  - bootutil
  - limport
  - lexport
  - lnode
  - lslurm
  - trinity_diagnosis
  - lmaster
  - lsosreport

luna2_named_include_file: /etc/named.luna.zones
luna2_named_zone_dir: /var/lib/named

luna2_cluster:
  ha: false
  nosharedip: false
  controllers:
    hostnames: 'controller1'
    ip_addresses: '10.141.255.254'
  frontend_address: '10.141.255.254'
  frontend_hostname: 'controller'
  networks:
  - name: 'cluster'
    function: 'default'
    ip: '10.141.0.0'
    prefix: '16'
    start_ip: '10.141.200.1'
    end_ip:  '10.141.210.254'
    type: 'ethernet'
  - name: 'ipmi'
    function: 'bmc'
    ip: '10.148.0.0'
    prefix: '16'
    type: 'ethernet'
  - name: 'ib'
    function: 'low-latency'
    ip: '10.149.0.0'
    prefix: '16'
    type: 'infiniband'

luna2_noarch_pip_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}"

luna2_key: CwSQcHNqiLSHXQaCDtAF2414e3muXgmpht6ocVA2xGs=

luna2_aarch64_ipxe_files: "https://boot.ipxe.org/arm64-efi"
luna2_x86_64_ipxe_files: "https://boot.ipxe.org"

luna2_download_all_arch_ipxe_files: true
