---
# vars file for luna

slurm_packages:
  - slurm
  - slurm-contribs
  - slurm-devel
  - slurm-munge
  - slurm-openlava
  - slurm-pam_slurm
  - slurm-perlapi
  - slurm-plugins
  - slurm-slurmdbd
  - slurm-sql
  - slurm-torque

slurm_conf_path: '/etc/slurm'
slurm_spool_path: '/var/spool/slurm'
slurm_log_path: '/var/log/slurm'

slurm_user_id: 891
slurm_group_id: 891

slurm_ctrl: 'controller'
slurm_ctrl_ip: '127.0.0.1'
slurm_ctrl_list: 'controller1,controller2'

enable_slurm_pam: false

slurmdbd_sql_user: 'slurm_accounting'
slurmdbd_sql_db: 'slurm_accounting'

munge_user_id: 892
munge_group_id: 892

munge_conf_path: '/etc/munge'
