---

sss_packages:
  - sssd
  - sssd-kcm
  - sssd-ldap
  - sssd-tools
  - libnfsidmap-sss
  - libsss_certmap0
  - libsss_idmap0
  - libsss_nss_idmap0
  - libnss_usrfiles2
  - pam_ssh

sssd_config_location: /etc/sssd
