---
ood_luna_apps_version: 2.0.latest
ood_luna_apps_url: https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}/ood/trinityx-ood-{{ ood_luna_apps_version }}.tar.gz # noqa: yaml[line-length]
ood_apps_admin_group: admins

ood_apps_path: /var/www/ood/apps/sys/

ood_apps_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'

ood_apps_arch: "{{ ood_apps_arch_map[system_arch] | default(system_arch) }}"


ood_apps:
  
  - name: jupyter
    type: bc
    node_rpms:
      - name: [python3.11, python3.11-pip]
    node_apts:
      - name: [python3, python3-pip, python3-venv]
  
  - name: codeserver
    type: bc
    node_rpms:
      - name: "https://github.com/coder/code-server/releases/download/v4.89.0/code-server-4.89.0-{{ ood_apps_arch }}.rpm"
        no_gpgcheck: true
    node_apts:
      - name: "https://github.com/coder/code-server/releases/download/v4.89.0/code-server_4.89.0_{{ ood_apps_arch }}.deb"
  
  - name: desktop
    override: true
    type: bc
    props:
      idle_timeout: 3600
      desktops:
        - xfce
      desktops_default: xfce
    node_rpms:
    - name: https://yum.osc.edu/ondemand/4.0/ondemand-release-compute-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
      no_gpgcheck: true
    - name: ["turbovnc", "python3-websockify", "dbus-x11", "@xfce"]
      enablerepo: crb
    tasks: ["desktop.yml"]

  - name: bmcsetup
    type: trinity
    mode: "0750"
  - name: cluster
    type: trinity
    mode: "0750"
  - name: group
    type: trinity
    mode: "0750"
  - name: network
    type: trinity
    mode: "0750"
  - name: node
    type: trinity
    mode: "0750"
  - name: osimage
    type: trinity
    mode: "0750"
  - name: otherdev
    type: trinity
    mode: "0750"
  - name: secrets
    type: trinity
    mode: "0750"
  - name: service
    type: trinity
    mode: "0750"
  - name: switch
    type: trinity
    mode: "0750"
  - name: control
    type: trinity
    mode: "0750"
  - name: users
    type: trinity
    mode: "0750"
  - name: osimagetag
    type: trinity
    mode: "0750"
  - name: monitor
    type: trinity
    mode: "0750"
  - name: dns
    type: trinity
    mode: "0750"
  - name: slurm
    type: trinity
    mode: "0750"
  - name: infiniband
    type: trinity
    mode: "0750"
    tasks: ["infiniband.yml"]
  - name: rack
    type: trinity
    mode: "0750"
  - name: alertx
    type: trinity
    mode: "0750"
    tasks: ["alertx.yml"]
  - name: passwd
    type: trinity
    mode: "0755"
    tasks: ["passwd.yml"]
  
    
  - name: system-status
    mode: "0000"
  - name: shell
    override: true
    mode: "0750"
    props:
      lchroot_wrapper_path: /usr/local/sbin/ood_lchroot_wrapper
    tasks: ["lchroot.yml"]

  - name: prometheus
  - name: alertmanager
    mode: "0750"
  - name: grafana
