---
# vars file for rsyslog

syslog_forwarding_rules: []
#syslog_forwarding_rules:
#  - name: default
#    proto: 'tcp'
#    port: 514
#    host: 'remote-host'
#    facility: '#*'
#    level: '*'

syslog_listeners: []
#syslog_listeners:
#  - name: default
#    proto: tcp
#    port: 514

syslog_file_template_rules: []
#syslog_file_template_rules:
#  - name: default
#    type: string
#    content: '/var/log/cluster-messages/%HOSTNAME%.messages'
#    field: '$fromhost-ip'
#    criteria: startswith
#    rule: '{{ "10.141.0.0".split(".")[:16//8]|join(".") }}'

rsyslog_config_location: /etc/rsyslog.d/
rsyslog_service: rsyslog
