---
# defaults file for scripts


config_manager_noarch_pip_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/additional/noarch/pip/{{ trix_stream }}"
config_manager_wheel: "trinityx_config_manager-2.0.latest-py3-none-any.whl"

scripts_managed_files:
  - /etc/genders
  - /etc/slurm/slurm-nodes.conf
  - /etc/slurm/slurm-partitions.conf

scripts_managed_block_comment1: "# TrinityX will only manage inside 'TrinityX Managed block'."
scripts_managed_block_comment2: "# If manual override is desired, the 'TrinityX Managed block' can be removed."
scripts_managed_block_start_delimiter: "#### TrinityX Managed block start ####"
scripts_managed_block_end_delimiter:   "#### TrinityX Managed block end   ####"
scripts_managed_block_start_regex:     "#### (TrinityX|TrinityX-OOD) Managed block start ####"
scripts_managed_block_end_regex:       "#### (TrinityX|TrinityX-OOD) Managed block end   ####"
