---
- name: Copy the nvidia Exporter systemd service file
  template:
    src: prometheus-nvidia-exporter.service.j2
    dest: /etc/systemd/system/prometheus-nvidia-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-nvidia-exporter

- name: Allow nvidia Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ prometheus_nvidia_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Configure prometheus nvidia-exporter if prometheus_nvidia_exporter_sd_file is defined
  blockinfile:
    path: "{{ prometheus_nvidia_exporter_sd_file }}"
    block: |
      {% for target_ip, target_hostname, target_domain in prometheus_nvidia_exporter_targets %}
      - targets:
        - {{ target_ip }}:{{ prometheus_nvidia_exporter_web_listen_port }}
        labels:
          exporter: nvidia
          luna_group: controller
          hostname: {{ target_hostname }}.{{ target_domain }}
      {% endfor %}
    marker: "### {mark} ANSIBLE MANAGED BLOCK ({{ ansible_fqdn }}.prometheus_nvidia_exporter)"
  when:
    - prometheus_nvidia_exporter_sd_file is defined