---
- name: Create the prometheus_nvidia_exporter group
  group:
    name: "{{ prometheus_nvidia_exporter_system_group }}"
    state: present
    system: true
  when: prometheus_nvidia_exporter_system_group != "root"

- name: Create the prometheus_nvidia_exporter user
  user:
    name: "{{ prometheus_nvidia_exporter_system_user }}"
    group: "{{ prometheus_nvidia_exporter_system_group }}"
    groups: "{{ prometheus_nvidia_exporter_additional_system_groups }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: prometheus_nvidia_exporter_system_user != "root"

- name: Create prometheus_nvidia_exporter_binary_install_dir
  file:
    path: "{{prometheus_nvidia_exporter_binary_install_dir}}"
    state: directory
    mode: 0755

- name: Create log dir if prometheus_nvidia_exporter_log_dir is defined
  ansible.builtin.file:
    path: "{{ prometheus_nvidia_exporter_log_dir }}"
    state: directory
    mode: 0755
  when:
    - prometheus_nvidia_exporter_log_dir is defined

- name: "Download prometheus-nvidia-exporter binary from {{prometheus_nvidia_exporter_binary_url}} to local folder"
  get_url:
    url: "{{ prometheus_nvidia_exporter_binary_url }}"
    dest: "{{prometheus_nvidia_exporter_binary_install_dir}}/prometheus-nvidia-exporter"
    mode: 0755
  register: _download_archive
  until: _download_archive is succeeded
  retries: 10
  delay: 15
