---
- block:
  - name: Clone git repository for Jupyter Notebook Interactive App
    git:
      repo: https://github.com/OSC/bc_example_jupyter.git
      dest: "{{ trix_ood }}/{{ ood_version }}/trinity_jupyter"
      force: true

  - name: Reset permissions for Jupyter Notebook Interactive App
    file:
      path: "{{ trix_ood }}/{{ ood_version }}/trinity_jupyter"
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: u=rw,g=r,o=r,a-x+X

  - name: Set permissions for template files
    file:
      path: "{{ trix_ood }}/{{ ood_version }}/trinity_jupyter/template"
      state: directory
      recurse: yes
      mode: +x

  - name: Render environment module for Jupyter Notebook Interactive App to load Python virtual environment
    template:
      src: 'jupyter/python-module.lua.j2'
      dest: '{{ trix_shared }}/modulefiles/ood-jupyter-python.lua'
      mode: '0644'
      owner: root
      group: root

  - name: Render submit script for Jupyter Notebook Interactive App
    template:
      src: 'jupyter/form.yml.j2'
      dest: "{{ trix_ood }}/{{ ood_version }}/trinity_jupyter/form.yml"
      mode: '0644'
      owner: root
      group: root

  - name: Creating Symlink for Jupyter Notebook Interactive App
    file:
      src: "{{ trix_ood }}/{{ ood_version }}/trinity_jupyter"
      dest: "/var/www/ood/apps/sys/trinity_jupyter"
      state: link
      # force: yes
      owner: root
      group: root

  when:
  - on_controller|default(False)
  - ansible_connection not in 'chroot'

- block:
  - name: Install python3-pip dependency for Jupyter Notebook
    apt:
      name:
      - python3-pip
      - python3-venv
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == 'Debian'

  - name: Install python3-pip dependency for Jupyter Notebook
    dnf:
      name: python3-pip
      state: present
      disable_gpg_check: true
    when: ansible_facts['os_family'] == "RedHat"
    retries: "{{ rpm_retries | default(3) }}"
    delay: "{{ rpm_delay | default(15) }}"

  - name: Create Python virtual environment for Jupyter Notebook
    shell: "python3 -m venv /opt/ood-jupyter-python"
    when: ansible_connection in 'chroot'
