---
# vars file for packages 

install_infiniband: false 

packages_packages:
  - epel-release

tunables_packages:
  - OpenIPMI
  - bash-completion
  - bc
  - bind-utils
  - bison
  - byacc
  - bzip2
  - createrepo
  - curl
  - dejavu-sans-fonts
  - dmidecode
  - ethtool
  - gawk
  - gcc
  - gdisk
  - git
  - gzip
  - haveged
  - hdparm
  - htop
  - hwloc
  - hwloc-libs
  - hwloc-plugins
  - hwloc-devel
  - infiniband-diags
  - iperf3
  - ipmitool
  - kernel-devel
  - kernel-headers
  - kernel-tools
  - less
  - libevent
  - libevent-devel
  - libfabric
  - libgfortran
  - libibverbs
  - libpcap
  - libpciaccess
  - librdmacm
  - libtool-ltdl
  - lm_sensors
  - lsof
  - make
  - mcelog
  - minicom
  - mlocate
  - moreutils
  - moreutils-parallel
  - msr-tools
  - mtr
  - nc
  - ncurses-term
  - net-tools
  - numactl
  - numactl-libs
  - numactl-devel
  - openssh-clients
  - openssh-server
  - parted
  - patch
  - pciutils
  - perf
  - python3-policycoreutils
  - psmisc
  - rsync
  - screen
  - sg3_utils
  - smartmontools
  - sshpass
  - strace
  - sudo
  - sysstat
  - tcpdump
  - telnet
  - tftp
  - time
  - tmux
  - tree
  - usbutils
  - util-linux
  - vim
  - wget
  - xorg-x11-xauth
  - yum-plugin-versionlock
  - yum-utils
  - mc
  - libhugetlbfs
  - libhugetlbfs-utils
  - libhugetlbfs-devel
  - automake
  - expect
  - unzip
  - dosfstools
  - grub2-efi-x64
  - shim-x64
  - efibootmgr
  - lbzip2
  - python2
  - tar
