---

# controller
- block:
  - include_tasks: cli.yml
  - include_tasks: drainer.yml
  when:
    - on_controller
    - not in_image

# below for images
- block:
  - name: Render AlertX hook script
    template:
      src: 'alertx-hook.sh.j2'
      dest: '/usr/local/sbin/alertx-hook.sh'
      owner: root
      group: root
      mode: 0700
    
  - name: Render /etc/systemd/system/alertx-hook.service
    template:
      src: 'alertx-hook.systemd.j2'
      dest: '/etc/systemd/system/alertx-hook.service'
      owner: root
      group: root
      mode: 0644

  - name: Enable luna services
    service:
      name: 'alertx-hook.service'
      enabled: true
  when: in_image or on_node|default(False)
