---

luna_image_path: /trinity/images/nonexistent

luna_image_distribution_detect:
  - name: RedHat
    distribution: redhat
  - name: Ubuntu
    distribution: ubuntu
  - name: Debian
    distribution: ubuntu
  - name: OpenSuse
    distribution: opensuse
  - name: Suse
    distribution: opensuse
  - name: SLE
    distribution: opensuse

