---

ssl_cert_path: '/etc/ssl/certs'
ssl_cert_country: 'NL'
ssl_cert_locality: 'Amsterdam'
ssl_cert_organization: 'ClusterVision Solutions B.V.'
ssl_cert_state: 'Noord Holland'
ssl_cert_altname: 'controller.cluster'

ssl_cert_days: '3650'

ssl_cert_owner: 'root'
ssl_cert_owner_id: 0

ssl_cert_group: 'ssl'
ssl_cert_group_id: 881

ssl_ca_cert_store:
  - name: RedHat
    location: /etc/pki/ca-trust/source/anchors/
    update_trust: update-ca-trust
  - name: Debian
    location: /usr/local/share/ca-certificates/
    update_trust: update-ca-certificates
  - name: Suse
    location: /etc/pki/trust/anchors/
    update_trust: update_trust: mount -t proc none /proc; update-ca-certificates; umount -l /proc
  - name: SLE
    location: /etc/pki/trust/anchors/
    update_trust: update_trust: mount -t proc none /proc; update-ca-certificates; umount -l /proc
