---
ssl_cert_path: '/etc/ssl/certs'
ssl_cert_country: 'NL'
ssl_cert_locality: 'Amsterdam'
ssl_cert_organization: 'ClusterVision Solutions B.V.'
ssl_cert_state: 'Noord Holland'
ssl_cert_altname: 'controller.cluster'

ssl_cert_days: '3650'

ssl_cert_owner: 'root'
ssl_cert_owner_id: 0

ssl_cert_group: 'ssl'
ssl_cert_group_id: 881
