---

# commented out below dependency as running with just --tags=sssd will NOT
# trigger the 'restart sssd' handler! Why? ... only the gods know!

#dependencies:
#  - role: sssd
#    when: 
#      - enable_authentication | default(True)
#      - override | default(False)
