---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  set_fact:
    prometheus_slurm_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Ensure that prometheus_slurm_exporter_version is set
  assert:
    that:
      - prometheus_slurm_exporter_version is defined
      - prometheus_slurm_exporter_version | length > 0
  tags:
    - prometheus-slurm-exporter-install

- name: Register prometheus_slurm_exporter binary
  set_fact:
    prometheus_slurm_exporter_binary: "prometheus-slurm-exporter-{{ prometheus_slurm_exporter_version }}-{{ ansible_architecture }}"
  tags:
    - prometheus-slurm-exporter-install

- name: Ensure that prometheus_slurm_exporter binary exists in role's files
  assert:
    that:
      - prometheus_slurm_exporter_binary is defined
      - prometheus_slurm_exporter_binary | length > 0
      - prometheus_slurm_exporter_binary in lookup('fileglob', 'files/prometheus-slurm-exporter-*')
  tags:
    - prometheus-slurm-exporter-install
