---

- name: Loading controller firewall role
  include_tasks: "controller.yml"
  when: on_controller

- name: Loading node and images firewall role
  include_tasks: "nodes.yml"
  when: in_image | default(False)

- name: Loading login node and image firewall role
  include_tasks: "login.yml"
  when: in_login_image | default(False)
