---

- name: Loading controller password role
  include_tasks: "controller.yml"
  when: on_controller

- name: Loading node and images password role
  include_tasks: "nodes.yml"
  when: in_image | default(False)

