---
# vars file for environment-modules

envmodules_packages:
  - Lmod

envmodules_files_path: '{{ trix_shared }}/modulefiles'

envmodules_default_list: []
envmodules_list: '{{ envmodules_default_list + additional_env_modules|default([]) }}'

envmodules_skiproot: true
