---
# vars file for cv_support

cv_support_packages:
  - python-libs
  - tigervnc-server
  - firefox
  - icedtea-web
  - icewm

project_id: '000000'
ha: False
on_controller: False
trix_ctrl_ip: '127.0.0.1'
