---
# handler file for kea

- name: start kea-dhcp4
  service:
    name: kea-dhcp4
    state: started

- name: start kea-dhcp6
  service:
    name: kea-dhcp6
    state: started

- name: restart kea-dhcp4
  service:
    name: kea-dhcp4
    state: restarted

- name: restart kea-dhcp6
  service:
    name: kea-dhcp6
    state: restarted

- name: enable kea-dhcp4
  service:
    name: kea-dhcp4
    enabled: true

- name: enable kea-dhcp6
  service:
    name: kea-dhcp6
    enabled: true

