---
trinityx_repositories:
  - name: trix
    repo: https://updates.clustervision.com/trinityx/{{ trix_version }}/os/opensuse/{{ opensuse_release.split('/')|last }}/{{ system_arch }}
    gpgcheck: False
  - name: luna2
    repo: https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/opensuse/{{ opensuse_release.split('/')|last }}/{{ system_arch }}
    gpgcheck: False
  - name: luna2-noarch
    repo: https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/rpms
    gpgcheck: False


image_core_packages:
  - "NetworkManager"
  - "audit"
  - "bash"
  - "coreutils"
  - "dracut"
  - "dracut-tools"
  - "gettext-runtime"
  - "filesystem"
  - "firewalld"
  - "nss-systemd"
  - "nss-myhostname"
  - "nss_wrapper"
  - "glibc"
  - "grubby"
  - "hostname"
  - "iproute"
  - "iputils"
  - "irqbalance"
  - "kbd"
  - "kexec-tools"
  - "ncurses"
  - "tar"
  - "bzip2"
  - "lbzip2"
  - "parted"
  - "gpg2"
  - "net-tools"
  - "less"
  - "mc"
  - "openssh"
  - "openssh-clients"
  - "openssh-server"
  - "parted"
  - "plymouth"
  - "policycoreutils"
  - "kernel-default"
  - "openssh-clients"
  - "openssh-server"
  - "sudo"
  - "systemd"
  - "curl"
  - "wget"
  - "e2fsprogs"
  - "xfsprogs"
  - "ipmitool"
  - "util-linux"
  - "authselect"
  - "biosdevname"
  - "syslog-ng"
  - "vim-small"
  - "vim"
  - "tuned"
  - "cronie"
  - "sssd"
  - "sssd-kcm"
  - "lshw"
  - "lsscsi"
  - "sg3_utils"
  - "rdma-core"
  - "rdma-core"
  - "grub2"
  - "shim"
  - "bind-utils"
  - "efibootmgr"
  - "dosfstools"
  - "lvm2"
  - "mdadm"
  - "dmidecode"
  - "tpm-tools"
  - "tpm2-0-tss"
  - "tpm2.0-tools"
  - "libtpms0"
  - "aria2"
  - "luna2-client"

dracut_extras:
  - "/usr/sbin/mkswap"
  - "/usr/sbin/swapon"
  - "/usr/sbin/swaplabel"
  - "/usr/sbin/mkfs.vfat"
  - "/usr/sbin/mkfs.fat"
  - "/usr/sbin/mkdosfs"
  - "/usr/sbin/dosfslabel"
  - "/usr/sbin/fatlabel"
  - "/etc/mke2fs.conf" # https://bugzilla.redhat.com/show_bug.cgi?id=1893750
  - "/usr/sbin/mdadm"
  - "/usr/bin/top"
  - "/usr/sbin/fdisk"
  - "/usr/sbin/lspci"
  - "/usr/share/hwdata/pci.ids"
  - "/usr/bin/lsblk"
  - "/usr/bin/lsscsi"
  - "/usr/bin/tee"
  - "/usr/bin/lbzip2"
  - "/usr/bin/tpm2_pcrread"
  - "/usr/bin/aria2c"
  - "/usr/sbin/dmidecode"

image_reinstall_packages:
  - "kernel"

