---

ubuntu_distribution_source: https://ports.ubuntu.com/

ubuntu_distribution_release: jammy

image_core_packages:                                                                                                                                                                         
  - python3
  - mc
  - e2fsprogs
  - xfsprogs
  - net-tools
  - tar
  - bzip2
  - lbzip2
  - parted
  - gpg
  - ipmitool
  - linux-image-generic
  - ssh
  - curl
  - less
  - aria2
  - vim
  - coreutils
  - tpm2-tools
  - grepcidr
  - iputils-ping
  - netplan.io
  - dosfstools
  - efibootmgr
  - rsync

luna2_client_package: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/deb/luna2-client.deb"
