---
zabbix_packages:
  - php
  - php-fpm
  - zabbix-server-mysql
  - zabbix-web-mysql

zabbix_script_path: '/usr/lib/zabbix/'
zabbix_sql_db: 'zabbix'
zabbix_sql_user: 'zabbix'

zabbix_login: 'Admin'
zabbix_runtime_password: 'zabbix'

zabbix_mail_server: 'localhost'

zabbix_repository: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
