---

alertx_packages: []

alertx_noarch_pip_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/alertx/noarch/pip/{{ trix_stream }}"
alertx_cli_pip: alertx-1.0-py3-none-any.whl

alertx_drainer_base_dir: '{{ trix_local }}/alertx/drainer'
alertx_drainer_daemon_dir: "{{ alertx_drainer_base_dir }}/daemon"
alertx_drainer_ini_dir: "{{ alertx_drainer_base_dir }}/config"
alertx_drainer_log_dir: "/var/log/alertx"
