---
dependencies:
  - role: nginx
    when:
    - on_controller
    - not extend_image | default(False)
  - role: trix-tree
    when:
    - on_controller
    - not extend_image | default(False)
  - role: kea
    when:
    - luna2_use_kea | default(False)
    - on_controller
    - not extend_image | default(False)
