---
image_core_packages:
  - "@core"
  - "kernel"
  - "grub2"
  - "grub2-tools"
  - "tzdata"
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  - "https://updates.clustervision.com/userspace/userspace-release.x86_64.rpm"

image_luna_packages:
  - "luna-client"
