---
# vars file for cv_support

trix_tools:
  - 'slurmibtopology.sh'
  - 'request-remote-assistance'
  - 'request-remote-assistance-automated'

cv_support_packages:
  - tigervnc-server
  - firefox
  - icedtea-web
  - icewm
  - python3-pip
  - python3-requests
  - passlib

cv_support_pip_packages:
  - certifi

project_id: '000000'
trix_version: '0'
ha: 'False'
trix_ctrl_ip: '127.0.0.1'
