---
- name: Reload and restart prometheus-ipmi-exporter
  listen: "restart prometheus-ipmi-exporter"
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-ipmi-exporter
    state: restarted
