---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  set_fact:
    prometheus_amd_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Ensure that prometheus_amd_exporter_version is set
  assert:
    that:
      - prometheus_amd_exporter_version is defined
      - prometheus_amd_exporter_version | length > 0
  tags:
    - prometheus-amd-exporter-install

- name: Register prometheus_amd_exporter binary
  set_fact:
    prometheus_amd_exporter_binary: "prometheus-amd-exporter-{{ prometheus_amd_exporter_version }}-{{ system_arch }}"
  tags:
    - prometheus-amd-exporter-install

