---
- name: Install selinux python packages [RedHat]
  ansible.builtin.package:
    name: "{{ ['libselinux-python', 'policycoreutils-python']
           if ansible_python_version is version('3', '<') else
           ['python3-libselinux', 'python3-policycoreutils'] }}"
    state: present
  register: _install_selinux_packages
  until: _install_selinux_packages is success
  retries: 10
  delay: 15
  when: ansible_os_family | lower == "redhat"

- name: Install selinux python packages [clearlinux]
  ansible.builtin.package:
    name: sysadmin-basic
    state: present
  register: _install_selinux_packages
  until: _install_selinux_packages is success
  retries: 10
  delay: 15
  when:
    - ansible_distribution | lower == "clearlinux"

- name: Allow prometheus_node_exporter port in SELinux on RedHat OS family
  community.general.seport:
    ports: "{{ prometheus_node_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - enable_selinux|default(True)
