---

ood_rpms:
  - name: epel-release
  - name: https://yum.osc.edu/ondemand/4.0/ondemand-release-web-4.0-1.el9.noarch.rpm
    no_gpgcheck: true
  - name: ["nodejs24", "nodejs24-libs", "ruby", "ruby-libs", "ondemand", "luna2-python"]

