---
image_core_packages:                                                                                                                                                                         
  - "selinux-policy"
  - "selinux-policy-minimum"
  - "selinux-policy-targeted"
  - "epel-release"
  - "kernel"
  - "dracut"
  - "grub2"
  - "grub2-tools"
  - "grub2-efi-x64"
  - "grub2-efi-x64-modules"
  - "tzdata"
  - "bind-utils"
  - "shim-x64"
  - "efibootmgr"
  - "dosfstools"
  - "lvm2"
  - "mdadm"
  - "lbzip2"
  - "aria2"
  - "tpm2-tools"
  - "dmidecode"
  - "luna2-client"
  - "passwd"
  - "elfutils-libs"

image_reinstall_packages:
  - "kernel-core"

dracut_extras:
  - "/usr/sbin/mkswap"
  - "/usr/sbin/swapon"
  - "/usr/sbin/swaplabel"
  - "/usr/sbin/mkfs.vfat"
  - "/usr/sbin/mkfs.fat"
  - "/usr/sbin/mkdosfs"
  - "/usr/sbin/dosfslabel"
  - "/usr/sbin/fatlabel"
  - "/etc/mke2fs.conf" # https://bugzilla.redhat.com/show_bug.cgi?id=1893750
  - "/usr/sbin/mdadm"
  - "/usr/bin/top"
  - "/usr/sbin/fdisk"
  - "/usr/sbin/lspci"
  - "/usr/share/hwdata/pci.ids"
  - "/usr/bin/lsblk"
  - "/usr/bin/lsscsi"
  - "/usr/bin/tee"
  - "/usr/bin/lbzip2"
  - "/usr/bin/tpm2_pcrread"
  - "/usr/bin/aria2c"
  - "/usr/sbin/parted"
  - "/usr/bin/mount"
  - "/usr/sbin/dmidecode"

