---
image_core_packages:
  - "NetworkManager"
  - "audit"
  - "basesystem"
  - "bash"
  - "coreutils"
  - "cronie"
  - "curl"
  - "dnf"
  - "e2fsprogs"
  - "filesystem"
  - "firewalld"
  - "glibc"
  - "grubby"
  - "hostname"
  - "initscripts"
  - "iproute"
  - "iprutils"
  - "iputils"
  - "irqbalance"
  - "kbd"
  - "kexec-tools"
  - "less"
  - "man-db"
  - "ncurses"
  - "openssh-clients"
  - "openssh-server"
  - "parted"
  - "passwd"
  - "plymouth"
  - "policycoreutils"
  - "procps-ng"
  - "rootfiles"
  - "rpm"
  - "rsyslog"
  - "selinux-policy-targeted"
  - "setup"
  - "shadow-utils"
  - "sssd-common"
  - "sssd-kcm"
  - "sudo"
  - "systemd"
  - "tuned"
  - "util-linux"
  - "vim-minimal"
  - "xfsprogs"
  - "yum"
  - "NetworkManager-team"
  - "NetworkManager-tui"
  - "authselect"
  - "biosdevname"
  - "dnf-plugins-core"
  - "dracut-config-rescue"
  - "iwl100-firmware"
  - "iwl1000-firmware"
  - "iwl105-firmware"
  - "iwl135-firmware"
  - "iwl2000-firmware"
  - "iwl2030-firmware"
  - "iwl3160-firmware"
  - "iwl5000-firmware"
  - "iwl5150-firmware"
    #  - "iwl6000-firmware"
  - "iwl6000g2a-firmware"
  - "iwl6050-firmware"
  - "iwl7260-firmware"
  - "kernel-tools"
  - "libsysfs"
  - "linux-firmware"
  - "lshw"
  - "lsscsi"
  - "microcode_ctl"
  - "prefixdevname"
  - "sg3_utils"
  - "sg3_utils-libs"
  - "dracut-config-generic"
  - "dracut-network"
  - "initial-setup"
  - "rdma-core"
  - "selinux-policy-mls"
  - "tboot"
  - "kernel"
  - "grub2"
  - "grub2-tools"
  - "grub2-efi-x64"
  - "grub2-efi-x64-modules"
  - "tzdata"
  - "bind-utils"
  - "shim-x64"
  - "efibootmgr"
  - "dosfstools"
  - "lvm2"
  - "mdadm"
  - "lbzip2"
  - "aria2"
  - "tpm2-tools"
  - "dmidecode"
  - "haveged"
  - "luna2-client"

image_reinstall_packages:
  - "kernel-core"

image_remove_packages:
  - "curl-minimal"
#  - "coreutils-single"

dracut_extras:
  - "/usr/sbin/mkswap"
  - "/usr/sbin/swapon"
  - "/usr/sbin/swaplabel"
  - "/usr/sbin/mkfs.vfat"
  - "/usr/sbin/mkfs.fat"
  - "/usr/sbin/mkdosfs"
  - "/usr/sbin/dosfslabel"
  - "/usr/sbin/fatlabel"
  - "/etc/mke2fs.conf" # https://bugzilla.redhat.com/show_bug.cgi?id=1893750
  - "/usr/sbin/mdadm"
  - "/usr/bin/top"
  - "/usr/sbin/fdisk"
  - "/usr/sbin/lspci"
  - "/usr/share/hwdata/pci.ids"
  - "/usr/bin/lsblk"
  - "/usr/bin/lsscsi"
  - "/usr/bin/tee"
  - "/usr/bin/lbzip2"
  - "/usr/bin/tpm2_pcrread"
  - "/usr/bin/aria2c"
  - "/usr/sbin/dmidecode"

luna2_noarch_repo_package: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/rpms"
