---
# Install additional packages and tunables

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version}}.yaml"
  no_log: true
  ignore_errors: true

- name: Install additional packages
  yum:
    name: "{{ tunables_packages }}"
    state: present
    enablerepo: powertools
    disable_gpg_check: true
  tags: install-only
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Copy 91-hpc-limits.conf to /etc/security/limits.d
  template:
    src: '91-hpc-limits.conf.j2'
    dest: '/etc/security/limits.d/91-hpc-limits.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Copy 91-hpc-sysctl.conf to /etc/sysctl.d/
  template:
    src: '91-hpc-sysctl.conf.j2'
    dest: '/etc/sysctl.d/91-hpc-sysctl.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  notify: activate sysctls

- name: Setting compute performance tuned profile
  shell: "tuned-adm profile {{ compute_tuned_profile | default('hpc-compute') }}"
  when: in_image
  ignore_errors: true

- name: Setting controller performance tuned profile
  shell: "tuned-adm profile {{ controller_tuned_profile | default('throughput-performance') }}"
  when: on_controller
  ignore_errors: true

- block:
  - name: gather info of current configured nfs threads
    shell: "grep -A100 \"\\[nfsd\\]\" /etc/nfs.conf|grep '# threads' || echo ''"
    register: nfs_threads

  - name: Increasing NFS threads on controller
    lineinfile:
      path: /etc/nfs.conf
      regexp: '^{{ nfs_threads.stdout }}'
      line: 'threads=256'
    when: nfs_threads is defined and nfs_threads.stdout_lines|length == 1
  when: on_controller
